inputs: 

  port: 
    description: 'Port for node application to run'
    default: 1010

  environment:
    description: 'Environment for node application'
    default: 'DEV'

runs:

  using: "composite"

  steps:
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started
      shell: bash

    - name: Install dependencies
      run: npm install
      shell: bash

    - name: Install pm2
      run: sudo npm install -g pm2
      shell: bash
      
    # - name: Delete services
    #   run: pm2 delete ${{ inputs.environment }}
    #   shell: bash

    - name: Start service
      run: pm2 start -n ${{ inputs.environment }} index.js -- ${{ port }}
      shell: bash

    - name: Check service
      run: pm2 list
      shell: bash