# This is a basic workflow to help you get started with Actions

name: sample-book-app

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build

      # # Runs a single command using the runners shell
      # - name: build success
      #   run: echo build success

      # - name: check node version
      #   run: node -v

  deploy-dev:
    name: deploy DEV
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with: 
          port: 1234 # te j훮sakr카t portiem ar to, kas nor훮d카ts config
          environment: 'DEV'
      # # Runs a single command using the runners shell
      # - name: deploy success
      #   run: echo deployment to DEV has started

  tests-dev:
    name: tests DEV
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [deploy-dev]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # # Runs a single command using the runners shell
      # - name: tests success
      #   run: echo testing on DEV has started
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: 'pa3jans/api-automation'
          path: 'api-tests'
      - uses: ./.github/actions/tests
        with: 
          environment: 'BOOKS_DEV'

  deploy-stg:
    name: deploy STG
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [tests-dev]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # # Runs a single command using the runners shell
      # - name: deploy success
      #   run: echo deployment to STG has started
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with: 
          port: 1235
          environment: 'STG'

  tests-stg:
    name: tests STG
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [deploy-stg]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # # Runs a single command using the runners shell
      # - name: tests success
      #   run: echo testing on STG has started
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with: 
          environment: 'STG'

  deploy-prd:
    name: deploy PRD
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [tests-stg]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # # Runs a single command using the runners shell
      # - name: deploy success
      #   run: echo deployment to PRD has started
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with: 
          port: 1236
          environment: 'PRD'

  tests-prd:
    name: tests PRD
    # The type of runner that the job will run on
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    needs: [deploy-prd]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # # Runs a single command using the runners shell
      # - name: tests success
      #   run: echo testing on PRD has started
      - uses: actions/checkout@v4
      - uses: ./.github/actions/tests
        with: 
          environment: 'PRD'
